### ISSUE TITLE
Exception in All Creatures Scoring

### ISSUE THREAD

**Issue by rythos42** [rythos42/AgricolaScorer#12]
Checking the Google Play Console today (which I wish would e-mail me when there's a problem...) found this exception. I have no other repro steps except this. It was on an Android 6.0 Nexus 5.

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.geeksong.agricolascorer.model.AllCreaturesScore.getTotalScore()' on a null object reference
	at com.geeksong.agricolascorer.managers.AllCreaturesScoreManager.<init>(AllCreaturesScoreManager.java:19)
	at com.geeksong.agricolascorer.control.scoretabfactory.AllCreaturesScoreTabFactory.createTabContent(AllCreaturesScoreTabFactory.java:25)
	at android.widget.TabHost$FactoryContentStrategy.getContentView(TabHost.java:693)
	at android.widget.TabHost.setCurrentTab(TabHost.java:388)
	at android.widget.TabHost$2.onTabSelectionChanged(TabHost.java:158)
	at android.widget.TabWidget$TabClickListener.onClick(TabWidget.java:551)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21153)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by rythos42** [comment]
This may have also been fixed by the commit for #16. The code appears to have tried to get a Score from the GameCache and returned null, which causes this NullPointerException. 

There was an opportunity that a null name could cause this, or just a name that wasn't in the system somehow.

But the commit for #16 creates the Scores a little earlier in the process, in case that solved it.

I don't super like debugging by stack trace...
