### ISSUE TITLE
Exception in Android internals

### ISSUE THREAD

**Issue by rythos42** [rythos42/AgricolaScorer#13]
Again, checking the console today and found this exception. Android 4.4, Galaxy Note 3 Neo (hlite).

java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(16908298, class android.widget.ListView) with Adapter(class com.geeksong.agricolascorer.listadapter.CurrentPlayersAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1566)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:5137)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:4933)
	at android.view.View.dispatchTouchEvent(View.java:8161)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2428)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2151)
	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:4877)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2311)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1606)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2617)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2259)
	at android.view.View.dispatchPointerEvent(View.java:8369)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4656)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4214)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4237)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4348)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4245)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4405)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4214)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4237)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4245)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4214)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6594)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6508)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6479)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6444)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6674)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:138)
	at android.os.Looper.loop(Looper.java:131)
	at android.app.ActivityThread.main(ActivityThread.java:5692)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by rythos42** [comment]
his is a hack.
 I have no repro steps to tell how it happened. Because self.players is shared by many activities, it is likely that the ArrayList was modified, then someone pressed back to get to CreateGameActivity, which didn't reload itself, but did a layout and threw this exception.

Because I can't repro, I decided to heavy-hammer the situation by notifying the adapter inside this class, of any changes made to it.
